apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lp563z7fj-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/lp563z7fj-dotnet-basic